# Generated by Django 3.2.6 on 2021-08-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='identi',
            field=models.CharField(max_length=255, null=True, verbose_name='identi'),
        ),
    ]
