# Generated by Django 3.2.6 on 2021-08-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_bankuser_identi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='doctor',
            field=models.BooleanField(null=True, verbose_name='doctor'),
        ),
    ]
